//! Bit-for-bit parity between the Rust port and the TypeScript originals.
//!
//! `data/vectors.rs` is generated by `rust/tools/gen_vectors.mjs`, which imports
//! `src/core/PseudoRandom.ts` and `src/core/DetMath.ts` and records what they
//! actually produce. These tests therefore assert agreement with the shipped
//! implementation, not with an idealised spec.
//!
//! Every double comparison goes through `to_bits()`, so a single-ULP drift fails
//! loudly instead of hiding inside a tolerance.

#[path = "data/vectors.rs"]
mod vectors;

use openfront_core::detmath;
use openfront_core::pseudo_random::PseudoRandom;

fn eq_bits(label: &str, got: f64, want: u64) {
    let got_bits = got.to_bits();
    assert_eq!(
        got_bits, want,
        "{label}: got {got:?} (bits {got_bits:#018x}), TS bits {want:#018x}"
    );
}

// ---------------------------------------------------------------- PseudoRandom

#[test]
fn prng_raw_u32_stream_matches_ts() {
    assert_eq!(
        vectors::PRNG_STREAMS.len(),
        vectors::PRNG_SEEDS.len() * vectors::PRNG_STREAM_LEN
    );
    for (si, &seed) in vectors::PRNG_SEEDS.iter().enumerate() {
        let mut rng = PseudoRandom::new(seed);
        for i in 0..vectors::PRNG_STREAM_LEN {
            let at = si * vectors::PRNG_STREAM_LEN + i;
            assert_eq!(rng.next_u32(), vectors::PRNG_STREAMS[at], "seed {seed} step {i}");
        }
    }
}

#[test]
fn prng_next_double_matches_ts_exactly() {
    // The vector file stores the u32 numerator; `next()` is that value divided
    // by 2^32, which is exact in binary64, so this pins the double too.
    for (si, &seed) in vectors::PRNG_SEEDS.iter().enumerate() {
        let mut rng = PseudoRandom::new(seed);
        for i in 0..vectors::PRNG_STREAM_LEN {
            let raw = vectors::PRNG_STREAMS[si * vectors::PRNG_STREAM_LEN + i];
            assert_eq!(rng.next(), raw as f64 / 4_294_967_296.0, "seed {seed} step {i}");
        }
    }
}

#[test]
fn prng_next_int_matches_ts_over_many_ranges() {
    let n_ranges = vectors::PRNG_INT_RANGES.len();
    assert_eq!(
        vectors::PRNG_INT_VALUES.len(),
        vectors::PRNG_SEEDS.len() * n_ranges * vectors::PRNG_INT_COUNT
    );
    for (si, &seed) in vectors::PRNG_SEEDS.iter().enumerate() {
        for (ri, &(lo, hi)) in vectors::PRNG_INT_RANGES.iter().enumerate() {
            let mut rng = PseudoRandom::new(seed);
            let base = (si * n_ranges + ri) * vectors::PRNG_INT_COUNT;
            for k in 0..vectors::PRNG_INT_COUNT {
                assert_eq!(
                    rng.next_int(lo, hi),
                    vectors::PRNG_INT_VALUES[base + k],
                    "seed {seed} range [{lo}, {hi}) step {k}"
                );
            }
        }
    }
}

#[test]
fn prng_next_id_matches_ts() {
    let mut rng = PseudoRandom::new(vectors::PRNG_ID_SEED);
    for (i, want) in vectors::PRNG_IDS.iter().enumerate() {
        assert_eq!(&rng.next_id(), *want, "next_id step {i}");
    }
}

#[test]
fn prng_shuffle_matches_ts_permutations() {
    let input: Vec<u8> = (0..vectors::PRNG_SHUFFLE_LEN as u8).collect();
    for (si, &seed) in vectors::PRNG_SEEDS.iter().enumerate() {
        let mut rng = PseudoRandom::new(seed);
        let got = rng.shuffle_array(&input);
        let base = si * vectors::PRNG_SHUFFLE_LEN;
        for (k, &want) in vectors::PRNG_SHUFFLES[base..base + vectors::PRNG_SHUFFLE_LEN]
            .iter()
            .enumerate()
        {
            assert_eq!(got[k], want, "seed {seed} position {k}");
        }
    }
}

#[test]
fn prng_chance_matches_ts() {
    let mut rng = PseudoRandom::new(vectors::PRNG_CHANCE_SEED);
    for (i, &byte) in vectors::PRNG_CHANCE_BITS.iter().enumerate() {
        for bit in 0..8 {
            let want = (byte >> (7 - bit)) & 1 == 1;
            assert_eq!(rng.chance(vectors::PRNG_CHANCE_ODDS), want, "chance index {i} bit {bit}");
        }
    }
}

#[test]
fn prng_seed_equivalence_classes_match_ts() {
    // TS truncates the seed through `| 0`, so these must share a stream.
    let groups: &[(f64, f64)] = &[
        (0.0, 4_294_967_296.0),
        (42.9, 42.0),
        (-1.0, -4_294_967_297.0),
        (1_000_000.5, 1_000_000.0),
    ];
    for &(a, b) in groups {
        let mut ra = PseudoRandom::new(a);
        let mut rb = PseudoRandom::new(b);
        for i in 0..64 {
            assert_eq!(ra.next_u32(), rb.next_u32(), "{a} vs {b} step {i}");
        }
    }
}

// ---------------------------------------------------------------- DetMath

#[test]
fn detmath_exp_matches_ts_bits() {
    assert_eq!(vectors::DET_EXP_X.len(), vectors::DET_EXP_BITS.len());
    for (i, &x) in vectors::DET_EXP_X.iter().enumerate() {
        eq_bits(&format!("exp({x})"), detmath::exp(x), vectors::DET_EXP_BITS[i]);
    }
}

#[test]
fn detmath_log_matches_ts_bits() {
    assert_eq!(vectors::DET_LOG_X.len(), vectors::DET_LOG_BITS.len());
    for (i, &x) in vectors::DET_LOG_X.iter().enumerate() {
        eq_bits(&format!("log({x})"), detmath::log(x), vectors::DET_LOG_BITS[i]);
    }
}

#[test]
fn detmath_pow_matches_ts_bits() {
    assert_eq!(vectors::DET_POW_ARGS.len(), vectors::DET_POW_BITS.len());
    for (i, &(x, y)) in vectors::DET_POW_ARGS.iter().enumerate() {
        eq_bits(&format!("pow({x}, {y})"), detmath::pow(x, y), vectors::DET_POW_BITS[i]);
    }
}

#[test]
fn detmath_atan2_matches_ts_bits() {
    assert_eq!(vectors::DET_ATAN2_ARGS.len(), vectors::DET_ATAN2_BITS.len());
    for (i, &(y, x)) in vectors::DET_ATAN2_ARGS.iter().enumerate() {
        eq_bits(&format!("atan2({y}, {x})"), detmath::atan2(y, x), vectors::DET_ATAN2_BITS[i]);
    }
}

#[test]
fn detmath_pow2_matches_ts_bits() {
    assert_eq!(vectors::DET_POW2_N.len(), vectors::DET_POW2_BITS.len());
    for (i, &n) in vectors::DET_POW2_N.iter().enumerate() {
        eq_bits(&format!("pow2({n})"), detmath::pow2(n), vectors::DET_POW2_BITS[i]);
    }
}

/// Independent confirmation that the vectors really are the published TS
/// behaviour: `tests/core/__snapshots__/DetMath.test.ts.snap` pins these same
/// eight values as decimals.
#[test]
fn detmath_snapshot_values_are_reproduced() {
    let got = [
        detmath::exp(1.0),
        detmath::exp(-12.5),
        detmath::log(3.0),
        detmath::log(150_000.0),
        detmath::pow(50_000.0, 0.6),
        detmath::pow(1_234_567.0, 0.73),
        detmath::atan2(3.0, 4.0),
        detmath::atan2(-7.0, -2.0),
    ];
    assert_eq!(got.len(), vectors::DET_SNAPSHOT_BITS.len());
    for (i, v) in got.iter().enumerate() {
        eq_bits(&format!("snapshot {i}"), *v, vectors::DET_SNAPSHOT_BITS[i]);
    }
    // And the decimals printed in the vitest snapshot, to 15 significant digits.
    for (i, &d) in vectors::DET_SNAPSHOT_DECIMALS.iter().enumerate() {
        assert_eq!(format!("{:.15e}", got[i]), format!("{:.15e}", d), "snapshot decimal {i}");
    }
}

// ---------------------------------------------------------------- determinism

/// Regression guard: repeated construction from one seed must be stable, and a
/// cloned generator must continue the same stream. A future refactor that hides
/// state behind a shared handle would break this.
#[test]
fn generator_state_is_value_semantic() {
    let mut a = PseudoRandom::new(777.0);
    let mut b = a.clone();
    for _ in 0..128 {
        assert_eq!(a.next_u32(), b.next_u32());
    }
    assert_eq!(a, b);
}
