//! Port of `src/core/execution/utils/TribeNames.ts`.
//!
//! `resolveTribeNameData(mapType?)` merges the tribe-name themes referenced
//! by a map's `MapInfo` (from [`crate::maps_gen`]) into a prefix/suffix pool,
//! with three observable edges: an unknown theme name logs a `console.warn`
//! and is skipped, an empty merged pool falls back to the `default` theme,
//! and a missing `default` theme throws. `customTribes` rides through when
//! the map has a non-empty list.
//!
//! Faithfulness notes:
//!
//! * The theme lookup is exact-key only (same prototype-chain exclusion as
//!   `server_list` / `asset_urls`); the JSON object's keys are the only
//!   reachable ones in the domain.
//! * The fallback condition is `mergedPrefixes.length === 0 ||
//!   mergedSuffixes.length === 0` — an *or*, so a theme with an empty
//!   prefixes array but non-empty suffixes still triggers the fallback, and
//!   the default theme's entries are then appended to whatever survived
//!   (suffixes can end up duplicated). The vectors pin this through the
//!   blanked-theme override in `run_op`.
//! * The warn message interpolates the map *type value* (the wire name), not
//!   the id: `[TribeNames] Map "${mapType}" references unknown tribe name
//!   theme "${themeName}". Skipping.`
//! * The theme table is generated from `resources/tribeNameThemes.json` by
//!   `tools/gen_maps_rs.mjs` (the region between the `BEGIN/END GENERATED`
//!   markers).
//! * `run_op` models the capture's mutation of the exported theme record:
//!   `removed` names are absent from the record (unknown-theme branch),
//!   `blanked` names exist but have empty prefix *and* suffix arrays (the
//!   or-condition edge).

use crate::maps_gen::Tribe;

/// One `tribeNameThemes.json` entry.
pub struct Theme {
    pub name: &'static str,
    pub prefixes: &'static [&'static str],
    pub suffixes: &'static [&'static str],
}

/// The `TribeNameData` the TS function returns.
#[derive(Debug, PartialEq)]
pub struct TribeNameData {
    pub prefixes: Vec<String>,
    pub suffixes: Vec<String>,
    pub custom_tribes: Option<&'static [Tribe]>,
}

// BEGIN GENERATED — rewritten by tools/gen_maps_rs.mjs, do not edit by hand.
/// `tribeNameThemes.json`: the 17 themes in JSON key order.
pub static THEMES: &[Theme] = &[
    Theme {
        name: "default",
        prefixes: &[
            "Akkadian",
            "Babylonian",
            "Sumerian",
            "Hittite",
            "Phoenician",
            "Canaanite",
            "Minoan",
            "Mycenaean",
            "Etruscan",
            "Scythian",
            "Thracian",
            "Dacian",
            "Illyrian",
            "Median",
            "Chaldean",
            "Roman",
            "Greek",
            "Byzantine",
            "Persian",
            "Parthian",
            "Seleucid",
            "Ptolemaic",
            "Palmyrene",
            "Macedonian",
            "Carthaginian",
            "Ming",
            "Tang",
            "Song",
            "Yuan",
            "Mauryan",
            "Kushan",
            "Rajput",
            "Mughal",
            "Satavahana",
            "Vijayanagara",
            "Egyptian",
            "Nubian",
            "Kushite",
            "Aksumite",
            "Ethiopian",
            "Songhai",
            "Malian",
            "Ghanaian",
            "Benin",
            "Ashanti",
            "Zulu",
            "Tuareg",
            "Berber",
            "Kanem-Bornu",
            "Buganda",
            "Mossi",
            "Swahili",
            "Somali",
            "Wolof",
            "Umayyad",
            "Abbasid",
            "Ayyubid",
            "Fatimid",
            "Mamluk",
            "Seljuk",
            "Safavid",
            "Ottoman",
            "Almoravid",
            "Almohad",
            "Rashidun",
            "Ziyarid",
            "Frankish",
            "Visigothic",
            "Ostrogothic",
            "Viking",
            "Norman",
            "Saxon",
            "Anglo-Saxon",
            "Celtic",
            "Gaulish",
            "Carolingian",
            "Merovingian",
            "Capetian",
            "Plantagenet",
            "Tudor",
            "Stuart",
            "Habsburg",
            "Romanov",
            "Lancaster",
            "York",
            "Bourbon",
            "Napoleonic",
            "British",
            "French",
            "Spanish",
            "Portuguese",
            "Dutch",
            "Russian",
            "German",
            "Italian",
            "Swedish",
            "Norwegian",
            "Danish",
            "Polish",
            "Hungarian",
            "Austrian",
            "Swiss",
            "Czech",
            "Slovak",
            "Serbian",
            "Croatian",
            "Bosnian",
            "Montenegrin",
            "Bulgarian",
            "Romanian",
            "Apache",
            "Sioux",
            "Cherokee",
            "Navajo",
            "Iroquois",
            "Inuit",
            "Arawak",
            "Carib",
            "Taino",
            "Aztec",
            "Mayan",
            "Incan",
            "Mapuche",
            "Guarani",
            "Tupi",
            "Yanomami",
            "Zuni",
            "Hopi",
            "Kiowa",
            "Comanche",
            "Shoshone",
            "Japanese",
            "Ryukyu",
            "Ainu",
            "Cham",
            "Khmer",
            "Thai",
            "Vietnamese",
            "Burmese",
            "Balinese",
            "Malay",
            "Filipino",
            "Mongolian",
            "Korean",
            "Tibetan",
            "Manchu",
            "Uyghur",
            "Hmong",
            "Karen",
            "Pyu",
            "Hawaiian",
            "Fijian",
            "Tongan",
            "Samoan",
            "Maori",
            "Micronesian",
            "Hebrew",
            "Armenian",
            "Circassian",
            "Georgian",
            "Kurdish",
            "Turkic",
            "Kazakh",
            "Uzbek",
            "Kyrgyz",
            "Tajik",
            "Pashtun",
            "Baloch",
            "Afghan",
            "Kenyan",
            "Ugandan",
            "Bhutanese",
            "Latin",
            "Moldovan",
            "Militant",
            "Spartan",
        ],
        suffixes: &[
            "Empire",
            "Dynasty",
            "Kingdom",
            "Queendom",
            "Sultanate",
            "Confederation",
            "Union",
            "Republic",
            "Caliphate",
            "Dominion",
            "Realm",
            "State",
            "Federation",
            "Territory",
            "Commonwealth",
            "League",
            "Duchy",
            "Province",
            "Protectorate",
            "Colony",
            "Mandate",
            "Free State",
            "Canton",
            "Region",
            "Nation",
            "Assembly",
            "Hierarchy",
            "Archduchy",
            "Grand Duchy",
            "Metropolis",
            "Cluster",
            "Alliance",
            "Tribunal",
            "Council",
            "Confederacy",
            "Order",
            "Regime",
            "Syndicate",
            "Guild",
            "Corporation",
            "Patriarchy",
            "Matriarchy",
            "Legion",
            "Horde",
            "Clan",
            "Brotherhood",
            "Sisterhood",
            "Ascendancy",
            "Supremacy",
            "Tribe",
            "Army",
            "Dictatorship",
            "Country",
            "Oligarchy",
            "Monkdom",
            "Throng",
            "Host",
            "Area",
            "District",
            "Fief",
            "Wilderness",
            "Settlement",
            "Parliament",
            "Anarchy",
            "Democracy",
            "Autocracy",
        ],
    },
    Theme {
        name: "north_america",
        prefixes: &[
            "Apache",
            "Sioux",
            "Cherokee",
            "Navajo",
            "Iroquois",
            "Inuit",
            "Arawak",
            "Carib",
            "Taino",
            "Aztec",
            "Mayan",
            "Zuni",
            "Hopi",
            "Kiowa",
            "Comanche",
            "Shoshone",
            "Cree",
            "Ojibwe",
            "Seminole",
            "Cheyenne",
            "Pawnee",
            "Mohawk",
            "Huron",
            "Tlingit",
            "Haida",
            "Nez Perce",
            "Crow",
            "Blackfoot",
            "Pueblo",
            "Mi'kmaq",
            "Algonquin",
            "Wampanoag",
            "Potawatomi",
            "Shawnee",
            "Chickasaw",
            "Choctaw",
            "Creek",
            "Canadian",
            "American",
            "Mexican",
            "Texan",
            "Californian",
            "Quebecois",
            "Acadian",
            "Louisianan",
            "Appalachian",
            "Yankee",
            "Frontiersman",
        ],
        suffixes: &[
            "Nation",
            "Confederation",
            "Territory",
            "Federation",
            "Republic",
            "State",
            "Province",
            "Colony",
            "Commonwealth",
            "Dominion",
            "Council",
            "Assembly",
            "Tribe",
            "Clan",
            "League",
            "Alliance",
            "Union",
            "Band",
            "Settlement",
            "Frontier",
            "Range",
            "Heartland",
            "Homeland",
            "Territories",
        ],
    },
    Theme {
        name: "south_america",
        prefixes: &[
            "Incan",
            "Mapuche",
            "Guarani",
            "Tupi",
            "Yanomami",
            "Quechua",
            "Aymara",
            "Chibcha",
            "Muisca",
            "Taíno",
            "Carib",
            "Wari",
            "Chimu",
            "Nazca",
            "Moche",
            "Olmec",
            "Zapotec",
            "Mixtec",
            "Toltec",
            "Brazilian",
            "Argentine",
            "Chilean",
            "Colombian",
            "Peruvian",
            "Venezuelan",
            "Ecuadorian",
            "Bolivian",
            "Paraguayan",
            "Uruguayan",
            "Guyanese",
            "Surinamese",
            "Patagonian",
            "Amazonian",
            "Andean",
            "Gaucho",
            "Carioca",
            "Porteño",
            "Cordobés",
            "Bogotano",
            "Limeño",
        ],
        suffixes: &[
            "Empire",
            "Kingdom",
            "Republic",
            "Confederation",
            "Federation",
            "State",
            "Nation",
            "Territory",
            "Province",
            "Chiefdom",
            "Dynasty",
            "Alliance",
            "League",
            "Council",
            "Tribe",
            "Clan",
            "Collective",
            "Domain",
            "Realm",
            "Heartland",
            "Amazonia",
            "Patagonia",
            "Andes",
            "Pampas",
        ],
    },
    Theme {
        name: "europe",
        prefixes: &[
            "Roman",
            "Greek",
            "Byzantine",
            "Frankish",
            "Visigothic",
            "Ostrogothic",
            "Viking",
            "Norman",
            "Saxon",
            "Anglo-Saxon",
            "Celtic",
            "Gaulish",
            "Carolingian",
            "Merovingian",
            "Capetian",
            "Plantagenet",
            "Tudor",
            "Stuart",
            "Habsburg",
            "Romanov",
            "Lancaster",
            "York",
            "Bourbon",
            "Napoleonic",
            "British",
            "French",
            "Spanish",
            "Portuguese",
            "Dutch",
            "Russian",
            "German",
            "Italian",
            "Swedish",
            "Norwegian",
            "Danish",
            "Polish",
            "Hungarian",
            "Austrian",
            "Swiss",
            "Czech",
            "Slovak",
            "Serbian",
            "Croatian",
            "Bosnian",
            "Montenegrin",
            "Bulgarian",
            "Romanian",
            "Finnish",
            "Estonian",
            "Latvian",
            "Lithuanian",
            "Irish",
            "Scottish",
            "Welsh",
            "Basque",
            "Galician",
            "Sardinian",
            "Sicilian",
            "Venetian",
            "Florentine",
            "Genoese",
            "Milanese",
            "Prussian",
            "Bavarian",
            "Teutonic",
            "Knights Templar",
            "Crusader",
            "Papal",
            "Holy Roman",
        ],
        suffixes: &[
            "Kingdom",
            "Empire",
            "Republic",
            "Duchy",
            "Grand Duchy",
            "Archduchy",
            "County",
            "Principality",
            "Barony",
            "Lordship",
            "March",
            "Shire",
            "Fief",
            "Realm",
            "Dominion",
            "Crown",
            "Dynasty",
            "House",
            "Order",
            "League",
            "Confederation",
            "Alliance",
            "Pact",
            "Union",
            "Federation",
            "Commonwealth",
            "State",
            "Nation",
            "Province",
            "Territory",
        ],
    },
    Theme {
        name: "africa",
        prefixes: &[
            "Egyptian",
            "Nubian",
            "Kushite",
            "Aksumite",
            "Ethiopian",
            "Songhai",
            "Malian",
            "Ghanaian",
            "Benin",
            "Ashanti",
            "Zulu",
            "Tuareg",
            "Berber",
            "Kanem-Bornu",
            "Buganda",
            "Mossi",
            "Swahili",
            "Somali",
            "Wolof",
            "Yoruba",
            "Igbo",
            "Hausa",
            "Fulani",
            "Maasai",
            "Kikuyu",
            "Shona",
            "Luba",
            "Lunda",
            "Kongo",
            "Lozi",
            "Tswana",
            "Sotho",
            "Xhosa",
            "Rwandan",
            "Burundian",
            "Baganda",
            "Bamileke",
            "Fang",
            "San",
            "Khoikhoi",
            "Merina",
            "Sakalava",
            "Betsileo",
            "Matabele",
            "Rozvi",
            "Mutapa",
        ],
        suffixes: &[
            "Empire",
            "Kingdom",
            "Sultanate",
            "Caliphate",
            "Dynasty",
            "Chiefdom",
            "Confederation",
            "Republic",
            "State",
            "Territory",
            "Province",
            "Region",
            "Nation",
            "Tribe",
            "Clan",
            "Alliance",
            "League",
            "Council",
            "Assembly",
            "Federation",
            "Union",
            "Dominion",
            "Realm",
            "Colony",
            "Protectorate",
        ],
    },
    Theme {
        name: "asia",
        prefixes: &[
            "Ming",
            "Tang",
            "Song",
            "Yuan",
            "Mauryan",
            "Kushan",
            "Rajput",
            "Mughal",
            "Satavahana",
            "Vijayanagara",
            "Japanese",
            "Ryukyu",
            "Ainu",
            "Cham",
            "Khmer",
            "Thai",
            "Vietnamese",
            "Burmese",
            "Balinese",
            "Malay",
            "Filipino",
            "Mongolian",
            "Korean",
            "Tibetan",
            "Manchu",
            "Uyghur",
            "Hmong",
            "Karen",
            "Pyu",
            "Han",
            "Qin",
            "Jin",
            "Sui",
            "Zhou",
            "Shang",
            "Xia",
            "Choson",
            "Goguryeo",
            "Baekje",
            "Silla",
            "Goryeo",
            "Joseon",
            "Yamato",
            "Heian",
            "Tokugawa",
            "Ashikaga",
            "Kamakura",
            "Fujiwara",
            "Taira",
            "Minamoto",
            "Srivijayan",
            "Majapahit",
            "Mataram",
            "Ayutthayan",
            "Sukhothai",
            "Lanna",
            "Champa",
            "Dai Viet",
            "Khitan",
            "Jurchen",
            "Xiongnu",
            "Göktürk",
            "Tangut",
            "Timurid",
            "Gupta",
            "Pala",
            "Chola",
            "Pandya",
            "Rashtrakuta",
            "Chalukya",
            "Hoysala",
            "Kalinga",
        ],
        suffixes: &[
            "Dynasty",
            "Empire",
            "Kingdom",
            "Shogunate",
            "Sultanate",
            "Khanate",
            "Principality",
            "Republic",
            "State",
            "Confederation",
            "Horde",
            "Realm",
            "Province",
            "Commandery",
            "Satrapy",
            "Viceroyalty",
            "Mandate",
            "Regency",
            "Clan",
            "Domain",
            "Fief",
            "March",
            "Colony",
            "Protectorate",
            "Tributary",
        ],
    },
    Theme {
        name: "oceania",
        prefixes: &[
            "Hawaiian",
            "Fijian",
            "Tongan",
            "Samoan",
            "Maori",
            "Micronesian",
            "Polynesian",
            "Melanesian",
            "Papuan",
            "Aboriginal",
            "Torres Strait",
            "Australian",
            "New Zealand",
            "Tahitian",
            "Marquesan",
            "Rapa Nui",
            "Chamorro",
            "Carolinian",
            "Marshallese",
            "Palauan",
            "Nauruan",
            "Tuvaluan",
            "Niuean",
            "Cook Islander",
            "Tokelauan",
            "Wallisian",
            "Futunan",
            "New Caledonian",
            "Vanuatuan",
            "Solomon Islander",
            "Bougainvillean",
        ],
        suffixes: &[
            "Islands",
            "Nation",
            "Federation",
            "Confederation",
            "Kingdom",
            "Republic",
            "Commonwealth",
            "Territory",
            "Council",
            "Alliance",
            "League",
            "Union",
            "Domain",
            "Realm",
            "Parliament",
            "Assembly",
            "Tribal Council",
            "Clan",
            "Tribe",
            "Homelands",
            "Archipelago",
            "Atoll",
            "Lagoon",
        ],
    },
    Theme {
        name: "space",
        prefixes: &[
            "Andromedan",
            "Centaurian",
            "Sirian",
            "Arcturian",
            "Pleiadian",
            "Vegan",
            "Lyran",
            "Orion",
            "Antarian",
            "Procyon",
            "Aldebaran",
            "Rigelian",
            "Betelgeusian",
            "Denebian",
            "Altairian",
            "Fomalhautian",
            "Capellan",
            "Zeta",
            "Tau",
            "Epsilon",
            "Keplerian",
            "Gliesean",
            "Trappist",
            "Proximan",
            "Barnardian",
            "Wolfian",
            "Luytenian",
            "Rossian",
            "Cygnian",
            "Aquilan",
            "Draconian",
            "Pegasian",
            "Hydran",
            "Corvan",
            "Nebulan",
            "Quasar",
            "Pulsar",
            "Novan",
            "Stellar",
            "Cosmic",
            "Galactic",
            "Lunar",
            "Solar",
            "Astral",
            "Voidborn",
            "Starforged",
            "Nebulite",
            "Quantum",
            "Dark Matter",
        ],
        suffixes: &[
            "Dominion",
            "Empire",
            "Federation",
            "Confederacy",
            "Commonwealth",
            "Collective",
            "Hive",
            "Alliance",
            "Coalition",
            "Concordat",
            "Protectorate",
            "Mandate",
            "Territory",
            "Sector",
            "Cluster",
            "Nebula",
            "Constellation",
            "Armada",
            "Fleet",
            "Legion",
            "Order",
            "Syndicate",
            "Corporation",
            "Council",
            "Tribunal",
            "Ascendancy",
            "Supremacy",
            "Swarm",
            "Horde",
            "Brotherhood",
        ],
    },
    Theme {
        name: "fantasy",
        prefixes: &[
            "Dragon",
            "Elven",
            "Dwarven",
            "Orcish",
            "Goblin",
            "Fairy",
            "Shadow",
            "Crystal",
            "Storm",
            "Iron",
            "Steel",
            "Golden",
            "Silver",
            "Emerald",
            "Ruby",
            "Sapphire",
            "Obsidian",
            "Moonlit",
            "Starlit",
            "Twilight",
            "Dawn",
            "Dusk",
            "Eternal",
            "Ancient",
            "Arcane",
            "Mystic",
            "Enchanted",
            "Cursed",
            "Blessed",
            "Sacred",
            "Dark",
            "Light",
            "Frost",
            "Flame",
            "Thorn",
            "Raven",
            "Wolf",
            "Bear",
            "Eagle",
            "Lion",
            "Serpent",
            "Phoenix",
            "Griffin",
            "Unicorn",
            "Pegasus",
            "Troll",
            "Giant",
            "Fey",
            "Sylvan",
            "Abyssal",
            "Celestial",
            "Infernal",
            "Primordial",
            "Runed",
            "Warded",
        ],
        suffixes: &[
            "Kingdom",
            "Realm",
            "Dominion",
            "Empire",
            "Dynasty",
            "Order",
            "Covenant",
            "Pact",
            "Alliance",
            "Guild",
            "Circle",
            "Council",
            "Conclave",
            "Sanctum",
            "Citadel",
            "Throne",
            "Crown",
            "Spire",
            "Hollow",
            "Reach",
            "Bastion",
            "Haven",
            "Enclave",
            "Brotherhood",
            "Sisterhood",
            "Horde",
            "Legion",
            "Swarm",
            "Host",
            "House",
            "Clan",
            "Tribe",
            "Nation",
            "Domain",
        ],
    },
    Theme {
        name: "war",
        prefixes: &[
            "Iron",
            "Steel",
            "Thunder",
            "Lightning",
            "Blitz",
            "Vanguard",
            "Phalanx",
            "Spartan",
            "Gladiator",
            "Centurion",
            "Hussar",
            "Cossack",
            "Samurai",
            "Mongol",
            "Hoplite",
            "Legionary",
            "Musketeer",
            "Dragoon",
            "Lancer",
            "Commando",
            "Ranger",
            "Sentinel",
            "Warden",
            "Reaver",
            "Berserker",
            "Juggernaut",
            "Valkyrie",
            "Warlord",
            "Overlord",
            "General",
            "Marshal",
            "Captain",
            "Sergeant",
            "Colonel",
            "Admiral",
            "Commodore",
            "Tactician",
            "Strategist",
            "Warmonger",
            "Conqueror",
            "Liberator",
            "Insurgent",
            "Partisan",
            "Guerrilla",
            "Militia",
            "Mercenary",
            "Veteran",
            "Elite",
        ],
        suffixes: &[
            "Legion",
            "Army",
            "Corps",
            "Division",
            "Brigade",
            "Battalion",
            "Regiment",
            "Company",
            "Platoon",
            "Squad",
            "Phalanx",
            "Bastion",
            "Front",
            "Theater",
            "Warband",
            "Host",
            "Horde",
            "Force",
            "Command",
            "Operations",
            "Strike",
            "Assault",
            "Defense",
            "Garrison",
            "Outpost",
            "Fortress",
            "Citadel",
            "Arsenal",
            "Armory",
            "War Council",
            "High Command",
            "Tribunal",
        ],
    },
    Theme {
        name: "western",
        prefixes: &[
            "Cowboy",
            "Outlaw",
            "Sheriff",
            "Marshal",
            "Ranger",
            "Desperado",
            "Gunslinger",
            "Bounty Hunter",
            "Frontiersman",
            "Pioneer",
            "Prospector",
            "Rancher",
            "Bandit",
            "Renegade",
            "Drifter",
            "Wrangler",
            "Vaquero",
            "Buckaroo",
            "Lawman",
            "Deputy",
            "Scout",
            "Trapper",
            "Miner",
            "Preacher",
            "Doc",
            "Dusty",
            "Lonesome",
            "Wild",
            "Iron",
            "Silver",
            "Gold",
            "Copper",
            "Dakota",
            "Texas",
            "Arizona",
            "Montana",
            "Nevada",
            "Colorado",
            "Wyoming",
            "Oklahoma",
            "Kansas",
            "Nebraska",
            "New Mexico",
            "Deadwood",
            "Tombstone",
        ],
        suffixes: &[
            "Territory",
            "Frontier",
            "Range",
            "County",
            "District",
            "Settlement",
            "Outpost",
            "Trading Post",
            "Ranch",
            "Claim",
            "Camp",
            "Crossing",
            "Pass",
            "Gulch",
            "Canyon",
            "Ridge",
            "Valley",
            "Springs",
            "Flats",
            "Hollow",
            "Posse",
            "Gang",
            "Cartel",
            "Syndicate",
            "Alliance",
            "Confederation",
            "Sheriff's Office",
            "Marshal's Office",
            "Wagon Train",
            "Cattle Drive",
        ],
    },
    Theme {
        name: "under_ocean",
        prefixes: &[
            "Atlantean",
            "Abyssal",
            "Coral",
            "Deep",
            "Leviathan",
            "Kraken",
            "Nautilus",
            "Trident",
            "Pearl",
            "Tidal",
            "Submarine",
            "Bathyal",
            "Hadal",
            "Pelagic",
            "Neritic",
            "Benthic",
            "Abyssopelagic",
            "Mesopelagic",
            "Epipelagic",
            "Siren",
            "Merfolk",
            "Triton",
            "Poseidon",
            "Neptune",
            "Nereid",
            "Scylla",
            "Charybdis",
            "Lusca",
            "Jormungandr",
            "Tiamat",
            "Naga",
            "Selkie",
            "Kelpie",
            "Bunyip",
            "Djinn",
            "Undine",
            "Nixie",
            "Rusalka",
        ],
        suffixes: &[
            "Kingdom",
            "Depth",
            "Abyss",
            "Trench",
            "Reef",
            "Lagoon",
            "Atoll",
            "Archipelago",
            "Domain",
            "Realm",
            "Empire",
            "Dynasty",
            "Confederation",
            "Federation",
            "Collective",
            "Colony",
            "Hive",
            "Swarm",
            "School",
            "Council",
            "Conclave",
            "Order",
            "Brotherhood",
            "Sisterhood",
            "Horde",
            "Legion",
            "Host",
            "Current",
            "Tide",
            "Depths",
            "Waters",
            "Seas",
        ],
    },
    Theme {
        name: "tournament",
        prefixes: &[
            "Champion",
            "Knight",
            "Gladiator",
            "Warrior",
            "Paladin",
            "Hero",
            "Defender",
            "Guardian",
            "Protector",
            "Avenger",
            "Slayer",
            "Conqueror",
            "Victor",
            "Legend",
            "Titan",
            "Colossus",
            "Goliath",
            "Hercules",
            "Achilles",
            "Odysseus",
            "Leonidas",
            "Alexander",
            "Caesar",
            "Attila",
            "Genghis",
            "Napoleon",
            "Valor",
            "Honor",
            "Glory",
            "Triumph",
            "Dominance",
            "Supremacy",
            "Invincible",
            "Unstoppable",
            "Relentless",
            "Fearless",
            "Ruthless",
            "Merciless",
            "Undying",
            "Immortal",
            "Eternal",
            "Ascendant",
            "Apex",
        ],
        suffixes: &[
            "Arena",
            "Colosseum",
            "Ring",
            "Tournament",
            "Championship",
            "League",
            "Series",
            "Circuit",
            "Grand Prix",
            "Classic",
            "Invitational",
            "Open",
            "Cup",
            "Trophy",
            "Prize",
            "Crown",
            "Laurels",
            "Medal",
            "Award",
            "Honor Guard",
            "Elite",
            "Champions",
            "Masters",
            "Grandmasters",
            "Titans",
            "Legends",
            "Hall of Fame",
            "Order of Merit",
            "Circle",
        ],
    },
    Theme {
        name: "funny",
        prefixes: &[
            "Silly",
            "Wacky",
            "Zany",
            "Goofy",
            "Bonkers",
            "Loony",
            "Nutty",
            "Kooky",
            "Quirky",
            "Batty",
            "Daffy",
            "Dizzy",
            "Loopy",
            "Wobbly",
            "Funky",
            "Groovy",
            "Spunky",
            "Peppy",
            "Bouncy",
            "Jolly",
            "Merry",
            "Cheerful",
            "Giggly",
            "Snicker",
            "Chuckle",
            "Tickle",
            "Pickle",
            "Noodle",
            "Waffle",
            "Pancake",
            "Muffin",
            "Cupcake",
            "Donut",
            "Taco",
            "Burrito",
            "Nacho",
            "Pretzel",
            "Bagel",
            "Cookie",
            "Biscuit",
            "Crumpet",
            "Scone",
            "Pudding",
            "Custard",
            "Trifle",
            "Jellybean",
            "Gummy",
            "Lollipop",
        ],
        suffixes: &[
            "Squad",
            "Team",
            "Club",
            "Gang",
            "Crew",
            "Bunch",
            "Pack",
            "Mob",
            "Horde",
            "Swarm",
            "Flock",
            "Herd",
            "School",
            "Colony",
            "Band",
            "Troupe",
            "Ensemble",
            "Posse",
            "Clique",
            "Circle",
            "Society",
            "Association",
            "Fellowship",
            "Brotherhood",
            "Sisterhood",
            "Alliance",
            "Coalition",
            "League",
            "Union",
            "Federation",
            "Confederation",
            "Collective",
        ],
    },
    Theme {
        name: "scary",
        prefixes: &[
            "Dark",
            "Shadow",
            "Nightmare",
            "Ghoul",
            "Phantom",
            "Specter",
            "Wraith",
            "Revenant",
            "Banshee",
            "Dread",
            "Terror",
            "Horror",
            "Malice",
            "Venom",
            "Plague",
            "Pestilence",
            "Famine",
            "Death",
            "Doom",
            "Ruin",
            "Blight",
            "Curse",
            "Hex",
            "Jinx",
            "Spell",
            "Charm",
            "Hexen",
            "Witch",
            "Warlock",
            "Necromancer",
            "Lich",
            "Vampire",
            "Werewolf",
            "Zombie",
            "Skeleton",
            "Corpse",
            "Carrion",
            "Rot",
            "Decay",
            "Void",
            "Abyss",
            "Oblivion",
            "Entropy",
            "Chaos",
            "Madness",
            "Insanity",
            "Dementia",
            "Psychosis",
        ],
        suffixes: &[
            "Horde",
            "Legion",
            "Swarm",
            "Plague",
            "Scourge",
            "Blight",
            "Curse",
            "Nightmare",
            "Terror",
            "Dread",
            "Fear",
            "Panic",
            "Ruin",
            "Doom",
            "Death",
            "Reaping",
            "Harvest",
            "Culling",
            "Purge",
            "Extermination",
            "Brood",
            "Nest",
            "Lair",
            "Den",
            "Crypt",
            "Tomb",
            "Catacombs",
            "Coven",
            "Circle",
            "Order",
            "Cult",
            "Sect",
            "Brotherhood",
            "Pact",
        ],
    },
    Theme {
        name: "weird",
        prefixes: &[
            "Bizarre",
            "Strange",
            "Odd",
            "Peculiar",
            "Weird",
            "Eerie",
            "Uncanny",
            "Surreal",
            "Absurd",
            "Grotesque",
            "Macabre",
            "Eldritch",
            "Ethereal",
            "Spectral",
            "Gossamer",
            "Translucent",
            "Iridescent",
            "Opalescent",
            "Prismatic",
            "Kaleidoscopic",
            "Phantasmagoric",
            "Ineffable",
            "Inscrutable",
            "Paradoxical",
            "Impossible",
            "Inconceivable",
            "Unfathomable",
            "Inexplicable",
            "Anomalous",
            "Aberrant",
            "Deviant",
            "Atypical",
            "Unorthodox",
            "Heterodox",
            "Nonconformist",
            "Maverick",
            "Rogue",
            "Rebel",
            "Dissident",
            "Heretic",
        ],
        suffixes: &[
            "Collective",
            "Hive",
            "Swarm",
            "Network",
            "Matrix",
            "Web",
            "Lattice",
            "Grid",
            "Array",
            "Spectrum",
            "Prism",
            "Kaleidoscope",
            "Paradox",
            "Anomaly",
            "Aberration",
            "Enigma",
            "Mystery",
            "Riddle",
            "Puzzle",
            "Conundrum",
            "Dilemma",
            "Quandary",
            "Oxymoron",
            "Contradiction",
            "Dichotomy",
            "Juxtaposition",
            "Irony",
            "Satire",
            "Absurdity",
            "Nonsense",
        ],
    },
    Theme {
        name: "vs",
        prefixes: &[
            "Red",
            "Blue",
            "Green",
            "Yellow",
            "Orange",
            "Purple",
            "Pink",
            "Black",
            "White",
            "Grey",
            "Gold",
            "Silver",
            "Bronze",
            "Copper",
            "Iron",
            "Steel",
            "Alpha",
            "Beta",
            "Gamma",
            "Delta",
            "Epsilon",
            "Zeta",
            "Eta",
            "Theta",
            "North",
            "South",
            "East",
            "West",
            "Dawn",
            "Dusk",
            "Day",
            "Night",
            "Fire",
            "Water",
            "Earth",
            "Air",
            "Lightning",
            "Ice",
            "Nature",
            "Shadow",
            "Light",
            "Dark",
            "Order",
            "Chaos",
            "Life",
            "Death",
            "War",
            "Peace",
        ],
        suffixes: &[
            "Team",
            "Squad",
            "Crew",
            "Division",
            "Brigade",
            "Regiment",
            "Battalion",
            "Company",
            "Platoon",
            "Unit",
            "Force",
            "Command",
            "Operations",
            "Strike",
            "Assault",
            "Defense",
            "Vanguard",
            "Rearguard",
            "Flank",
            "Center",
            "Wing",
            "Corps",
            "Legion",
            "Army",
            "Horde",
            "Host",
            "Alliance",
            "Coalition",
            "League",
            "Union",
            "Federation",
            "Confederation",
        ],
    },
];
// END GENERATED

/// `getMapInfo`: find the `MapInfo` whose `type` equals the enum value.
fn get_map_info(map_type: &str) -> Option<&'static crate::maps_gen::MapInfo> {
    crate::maps_gen::MAPS.iter().find(|m| m.type_ == map_type)
}

/// The theme lookup with the capture's record-mutation overrides: `removed`
/// models `delete tribeNameThemes[name]`, `blanked` models emptying both
/// arrays.
fn lookup_theme<'a>(
    name: &str,
    removed: &[&str],
    blanked: &[&str],
) -> Option<(&'a [&'a str], &'a [&'a str])> {
    if removed.contains(&name) {
        return None;
    }
    if blanked.contains(&name) {
        return Some((&[], &[]));
    }
    THEMES.iter().find(|t| t.name == name).map(|t| (t.prefixes, t.suffixes))
}

/// `resolveTribeNameData(mapType?)`. The `console.warn` trace comes back as
/// the `Vec<String>`; `Err(())` models the missing-default throw.
pub fn resolve_tribe_name_data(
    map_type: Option<&str>,
    removed: &[&str],
    blanked: &[&str],
) -> (Vec<String>, Result<TribeNameData, ()>) {
    let mut warns: Vec<String> = Vec::new();
    if let Some(mt) = map_type {
        if let Some(info) = get_map_info(mt) {
            let theme_names: &[&str] = match info.themes {
                Some(t) if !t.is_empty() => t,
                _ => &["default"],
            };
            let mut merged_prefixes: Vec<String> = Vec::new();
            let mut merged_suffixes: Vec<String> = Vec::new();
            for theme_name in theme_names {
                match lookup_theme(theme_name, removed, blanked) {
                    None => {
                        warns.push(format!(
                            "[TribeNames] Map \"{mt}\" references unknown tribe name theme \"{theme_name}\". Skipping."
                        ));
                    }
                    Some((p, s)) => {
                        merged_prefixes.extend(p.iter().map(|x| x.to_string()));
                        merged_suffixes.extend(s.iter().map(|x| x.to_string()));
                    }
                }
            }
            // If all themes were unknown, fall back to default.
            if merged_prefixes.is_empty() || merged_suffixes.is_empty() {
                let Some((dp, ds)) = lookup_theme("default", removed, blanked) else {
                    return (warns, Err(()));
                };
                merged_prefixes.extend(dp.iter().map(|x| x.to_string()));
                merged_suffixes.extend(ds.iter().map(|x| x.to_string()));
            }
            let custom_tribes = match info.custom_tribes {
                Some(t) if !t.is_empty() => Some(t),
                _ => None,
            };
            return (
                warns,
                Ok(TribeNameData {
                    prefixes: merged_prefixes,
                    suffixes: merged_suffixes,
                    custom_tribes,
                }),
            );
        }
    }
    // No map type or map not found — use default theme.
    let Some((dp, ds)) = lookup_theme("default", removed, blanked) else {
        return (warns, Err(()));
    };
    (
        warns,
        Ok(TribeNameData {
            prefixes: dp.iter().map(|x| x.to_string()).collect(),
            suffixes: ds.iter().map(|x| x.to_string()).collect(),
            custom_tribes: None,
        }),
    )
}

// ---------------------------------------------------------------- vectors op
//
// A flat `f64` token runner shared by the golden replay and the wasm probe.
// Strings cross as `[len, u0, .. u(len-1)]` (UTF-16 code units).
//
// args: `[mapPresent, mapTypeString?, removedN, (removed)*, blankedN,
// (blanked)*]` (`mapPresent` 0 = no mapType argument).
// res: `[0, warnN, (warn)*, prefixN, (prefix)*, suffixN, (suffix)*,
// tribesPresent, tribeN, (name, coordPresent, x, y)*]` on success, `[1]`
// when the TS function throws (missing default theme).

struct Cur<'a>(&'a [f64], usize);
impl<'a> Cur<'a> {
    fn f(&mut self) -> f64 {
        let v = self.0[self.1];
        self.1 += 1;
        v
    }
    fn u(&mut self) -> usize {
        self.f() as usize
    }
    fn string(&mut self) -> String {
        let len = self.u();
        let units: Vec<u16> = (0..len).map(|_| self.f() as u16).collect();
        String::from_utf16_lossy(&units)
    }
}

fn push_string(out: &mut Vec<f64>, s: &str) {
    let units: Vec<u16> = s.encode_utf16().collect();
    out.push(units.len() as f64);
    out.extend(units.iter().map(|&u| u as f64));
}

fn push_strings(out: &mut Vec<f64>, list: &[String]) {
    out.push(list.len() as f64);
    for s in list {
        push_string(out, s);
    }
}

pub fn run_op(kind: u8, args: &[f64]) -> Vec<f64> {
    let mut out = Vec::new();
    if kind != 0 {
        return out;
    }
    let mut c = Cur(args, 0);
    let map_type = if c.u() == 1 { Some(c.string()) } else { None };
    let removed: Vec<String> = (0..c.u()).map(|_| c.string()).collect();
    let blanked: Vec<String> = (0..c.u()).map(|_| c.string()).collect();
    let removed_refs: Vec<&str> = removed.iter().map(|s| s.as_str()).collect();
    let blanked_refs: Vec<&str> = blanked.iter().map(|s| s.as_str()).collect();
    let (warns, res) = resolve_tribe_name_data(
        map_type.as_deref(),
        &removed_refs,
        &blanked_refs,
    );
    match res {
        Ok(data) => {
            out.push(0.0);
            push_strings(&mut out, &warns);
            push_strings(&mut out, &data.prefixes);
            push_strings(&mut out, &data.suffixes);
            match data.custom_tribes {
                Some(tribes) => {
                    out.push(1.0);
                    out.push(tribes.len() as f64);
                    for t in tribes {
                        push_string(&mut out, t.name);
                        match t.coordinates {
                            Some((x, y)) => {
                                out.push(1.0);
                                out.push(x);
                                out.push(y);
                            }
                            None => out.push(0.0),
                        }
                    }
                }
                None => out.push(0.0),
            }
        }
        Err(()) => out.push(1.0),
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_theme_when_no_map() {
        let (warns, Ok(data)) = resolve_tribe_name_data(None, &[], &[]) else {
            panic!("default theme exists");
        };
        assert!(warns.is_empty());
        assert_eq!(data.prefixes.len(), 176);
        assert_eq!(data.suffixes.len(), 66);
        assert_eq!(data.custom_tribes, None);
    }

    #[test]
    fn unknown_map_type_falls_back_to_default() {
        let (_, Ok(data)) = resolve_tribe_name_data(Some("NoSuchMap"), &[], &[])
        else {
            panic!();
        };
        assert_eq!(data.prefixes.len(), 176);
    }

    #[test]
    fn themes_merge_in_order() {
        // Achiran: europe (69/30) + scary (48/34).
        let (_, Ok(data)) = resolve_tribe_name_data(Some("Achiran"), &[], &[])
        else {
            panic!();
        };
        assert_eq!(data.prefixes.len(), 69 + 48);
        assert_eq!(data.suffixes.len(), 30 + 34);
    }

    #[test]
    fn custom_tribes_ride_through() {
        let (_, Ok(data)) = resolve_tribe_name_data(Some("Germany"), &[], &[])
        else {
            panic!();
        };
        assert!(data.custom_tribes.is_some());
    }

    #[test]
    fn unknown_theme_warns_and_skips() {
        // Aegean: europe + asia; remove europe -> one warn, asia survives.
        let (warns, Ok(data)) =
            resolve_tribe_name_data(Some("Aegean"), &["europe"], &[])
        else {
            panic!();
        };
        assert_eq!(
            warns,
            vec!["[TribeNames] Map \"Aegean\" references unknown tribe name theme \"europe\". Skipping.".to_string()]
        );
        assert_eq!(data.prefixes.len(), 72);
    }

    #[test]
    fn all_unknown_falls_back_to_default() {
        let (warns, Ok(data)) =
            resolve_tribe_name_data(Some("Aegean"), &["europe", "asia"], &[])
        else {
            panic!();
        };
        assert_eq!(warns.len(), 2);
        assert_eq!(data.prefixes.len(), 176);
    }

    #[test]
    fn blanked_prefixes_triggers_or_fallback() {
        // europe blanked (both arrays empty) -> merged empty -> default.
        let (_, Ok(data)) =
            resolve_tribe_name_data(Some("Alps"), &[], &["europe"])
        else {
            panic!();
        };
        assert_eq!(data.prefixes.len(), 176);
    }

    #[test]
    fn missing_default_throws() {
        let (_, res) = resolve_tribe_name_data(None, &["default"], &[]);
        assert!(res.is_err());
        let (_, res) =
            resolve_tribe_name_data(Some("Aegean"), &["default", "europe", "asia"], &[]);
        assert!(res.is_err());
    }
}
